### ISSUE TITLE
Dependencies in Readme

### ISSUE THREAD

**Issue by SFrav** [Submanifold/latex-mimosis#3]
It could be good to add links for two dependencies for compiling your example tex. One for [KOMA-script installation](https://komascript.de/node/2049) and another for the [minion pro font](http://fontsgeek.com/fonts/Minion-Pro-Regular/download).

**Comment by Submanifold** [comment]
Thanks for reporting this! I have updated the README accordingly. As for the issues with Minion Pro font, you can also skirt around them by selecting another font using `\setmainfont` in the preamble.

Closing this now; please reopen if necessary.
